= Monitoring Black Berry 10

== Basic network availability

=== ICMP

=== DNS name resolution

[source,xml]
----
<service name="DNS-Resolution-v4" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="2000"/>
    <parameter key="resolution-type" value="v4"/>
    <parameter key="rrd-repository" value="/opt/opennms/share/rrd/response"/>
    <parameter key="rrd-base-name" value="dns-res-v6"/>
    <parameter key="ds-name" value="dns-res-v6"/>
</service>
<service name="DNS-Resolution-v6" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="2000"/>
    <parameter key="resolution-type" value="v6"/>
    <parameter key="rrd-repository" value="/opt/opennms/share/rrd/response"/>
    <parameter key="rrd-base-name" value="dns-res-v6"/>
    <parameter key="ds-name" value="dns-res-v6"/>
</service>

<monitor service="DNS-Resolution-v4" class-name="org.opennms.netmgt.poller.monitors.DNSResolutionMonitor" />
<monitor service="DNS-Resolution-v6" class-name="org.opennms.netmgt.poller.monitors.DNSResolutionMonitor" />
----
== Baselining basic system metrics
Requirements for default system monitoring is installed and configured Windows SNMP agent + SNMP informant Standard.
http://www.snmp-informant.com/[SNMP Informant] is required to monitor Windows CPU utiliziation correctly.
Restart of the Windows System reogranises the CPU number SNMP index on Multi-Core systems.

=== Hard disk

=== CPU

.Category based thresholding configuration in `threshd-configuration.xml`
[source,xml]
----
<package name="TH-DISK-90">
    <filter>catincTH-DISK-90</filter>
    <include-range begin="1.1.1.1" end="254.254.254.254"/>
    <include-range begin="::1" end="ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff" />
    <service name="SNMP" interval="300000" user-defined="false" status="on">
        <parameter key="thresholding-group" value="TH-DISK-90"/>
    </service>
</package>

<package name="TH-CPU-90">
    <filter>catincTH-CPU-90</filter>
    <include-range begin="1.1.1.1" end="254.254.254.254"/>
    <include-range begin="::1" end="ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff" />
    <service name="SNMP" interval="300000" user-defined="false" status="on">
        <parameter key="thresholding-group" value="TH-CPU-90"/>
    </service>
</package>
----


.Configuration of Microsoft Windows and Linux CPU thresholds
[source,xml]
----
<group name="TH-CPU-90" rrdRepository="/var/lib/opennms/rrd/snmp/">
    <threshold description="cpu high threshold 90.0 rearmed 70.0 (Windows Single)"
               type="high" ds-type="sinfCpuInstance"
               value="90.0" rearm="70.0" trigger="5"
               ds-label="sinfCpuInstance"
               triggeredUEI="uei.opennms.org/threshold/windows/cpu/high/major/exceeded"
               rearmedUEI="uei.opennms.org/threshold/windows/cpu/high/major/rearmed"
               filterOperator="or" ds-name="sinfCpuPctProcTime">
        <resource-filter field="sinfCpuInstance">^\d+</resource-filter>
    </threshold>
    <threshold description="cpu high threshold 90.0 rearmed 70.0 (Windows Total)"
               type="high" ds-type="sinfCpuInstance"
               value="90.0" rearm="70.0" trigger="2"
               ds-label="sinfCpuInstance"
               triggeredUEI="uei.opennms.org/threshold/windows/cpu/high/major/exceeded"
               rearmedUEI="uei.opennms.org/threshold/windows/cpu/high/major/rearmed"
               filterOperator="or" ds-name="sinfCpuPctProcTime">
        <resource-filter field="sinfCpuInstance">^_Total</resource-filter>
    </threshold>
    <expression description="cpu high threshold 90.0 rearmed 70.0 (Unix Total)"
                type="high" ds-type="node"
                value="90.0" rearm="70.0"
                trigger="2"
                triggeredUEI="uei.opennms.org/threshold/unix/cpu/high/major/exceeded"
                rearmedUEI="uei.opennms.org/threshold/unix/cpu/high/major/rearmed"
                filterOperator="or"
                expression="(CpuRawUser+CpuRawNice+CpuRawSystem) / (CpuRawUser+CpuRawNice+CpuRawSystem+CpuRawIdle) *100"/>
----

.Configuration for generic hard disk thresholds
[source,xml]
----
</group>
    <group name="TH-DISK-90" rrdRepository="/var/lib/opennms/rrd/snmp/">
    <expression description="disk usage high 90.0 and rearmed 75.0"
                type="high" ds-type="hrStorageIndex"
                value="90.0" rearm="75.0" trigger="2"
                ds-label="hrStorageDescr"
                triggeredUEI="uei.opennms.org/threshold/disk/high/major/exceeded"
                rearmedUEI="uei.opennms.org/threshold/disk/high/major/rearmed"
                filterOperator="or"
                expression="hrStorageUsed / hrStorageSize * 100.0">
        <resource-filter field="hrStorageType">^\.1\.3\.6\.1\.2\.1\.25\.2\.1\.4$</resource-filter>
    </expression>
</group>
----

=== Events for OpenNMS Web UI

.Event configuration for thresholds in `Threshold.events.xml`
[source,xml]
----
<events>
    <event>
        <uei>uei.opennms.org/threshold/windows/cpu/high/major/exceeded</uei>
        <event-label>User-defined custom high threshold exceeded event for windows-cpu [Major]</event-label>
        <descr>
            &lt;p&gt;High threshold exceeded for %service% datasource %parm[ds]% on interface %interface% for node %nodelabel% (nodeId %nodeid%).&lt;/p&gt;&lt;br&gt;
            &lt;table style='width:50%; white-space: nowrap;'&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Data Source&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[ds]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Label&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[label]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Instance&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[instance]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Current Metric Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[value]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Threshold Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[threshold]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Rearm Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[rearm]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Trigger Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[trigger]%&lt;/td&gt;&lt;/tr&gt;
            &lt;/table&gt; &lt;/br&gt;&lt;p&gt;All parameters: %parm[all]%&lt;/p&gt;
        </descr>
        <logmsg dest="logndisplay">&lt;b&gt;&lt;a href='graph/results.htm?resourceId=node[%nodeid%].sinfCpuInstance[%parm[instance]%]&amp;reports=all'&gt;WINDOWS-CPU&lt;/b&gt;&lt;/a&gt; HIGH threshold &lt;b&gt;%parm[threshold]%&lt;/b&gt; exceeded with &lt;font color=#cc0000&gt;&lt;b&gt;%parm[value]%&lt;/b&gt;&lt;/font&gt;, on instance &lt;b&gt;%parm[label]%&lt;/b&gt;, for metric %parm[ds]%, on node %nodelabel%.</logmsg>
        <severity>Major</severity>
        <alarm-data auto-clean="false" alarm-type="1" reduction-key="%uei%:%dpname%:%nodeid%:%interface%:%parm[ds]%:%parm[threshold]%:%parm[trigger]%:%parm[rearm]%:%parm[label]%"/>
    </event>
    <event>
        <uei>uei.opennms.org/threshold/unix/cpu/high/major/exceeded</uei>
        <event-label>User-defined custom high threshold exceeded event for unix-cpu [Major]</event-label>
        <descr>
            &lt;p&gt;High threshold exceeded for %service% datasource %parm[ds]% on interface %interface% for node %nodelabel% (nodeId %nodeid%).&lt;/p&gt;&lt;br&gt;
            &lt;table style='width:50%; white-space: nowrap;'&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Data Source&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[ds]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Label&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[label]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Instance&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[instance]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Current Metric Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[value]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Threshold Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[threshold]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Rearm Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[rearm]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Trigger Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[trigger]%&lt;/td&gt;&lt;/tr&gt;
            &lt;/table&gt; &lt;/br&gt;&lt;p&gt;All parameters: %parm[all]%&lt;/p&gt;
        </descr>
        <logmsg dest="logndisplay">&lt;b&gt;&lt;a href='graph/results.htm?resourceId=node[%nodeid%].nodeSnmp[]&amp;reports=netsnmp.cpuStatsFull&amp;reports=netsnmp.cpuUsageFull'&gt;UNIX-CPU&lt;/b&gt;&lt;/a&gt; HIGH threshold &lt;b&gt;%parm[threshold]%&lt;/b&gt; exceeded with &lt;font color=#cc0000&gt;&lt;b&gt;%parm[value]%&lt;/b&gt;&lt;/font&gt;, for metric %parm[ds]%, on node %nodelabel%.</logmsg>
        <severity>Major</severity>
        <alarm-data auto-clean="false" alarm-type="1" reduction-key="%uei%:%dpname%:%nodeid%:%interface%:%parm[ds]%:%parm[threshold]%:%parm[trigger]%:%parm[rearm]%:%parm[label]%"/>
    </event>
    <event>
        <uei>uei.opennms.org/threshold/disk/high/major/exceeded</uei>
        <event-label>User-defined custom high threshold exceeded event for disk [Major]</event-label>
        <descr>
            &lt;p&gt;High threshold exceeded for %service% datasource %parm[ds]% on interface %interface% for node %nodelabel% (nodeId %nodeid%).&lt;/p&gt;&lt;br&gt;
            &lt;table style='width:50%; white-space: nowrap;'&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Data Source&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[ds]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Label&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[label]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Instance&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[instance]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Current Metric Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[value]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Threshold Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[threshold]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Rearm Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[rearm]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Trigger Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[trigger]%&lt;/td&gt;&lt;/tr&gt;
            &lt;/table&gt; &lt;/br&gt;&lt;p&gt;All parameters: %parm[all]%&lt;/p&gt;</descr>
        <logmsg dest="logndisplay">&lt;b&gt;DISK&lt;/b&gt; HIGH threshold &lt;b&gt;%parm[threshold]%&lt;/b&gt; exceeded with &lt;font color=#cc0000&gt;&lt;b&gt;%parm[value]%&lt;/b&gt;&lt;/font&gt;, on instance &lt;b&gt;%parm[label]%&lt;/b&gt;, for metric %parm[ds]%, on node %nodelabel%.</logmsg>
        <severity>Major</severity>
        <alarm-data auto-clean="false" alarm-type="1" reduction-key="%uei%:%dpname%:%nodeid%:%interface%:%parm[ds]%:%parm[threshold]%:%parm[trigger]%:%parm[rearm]%:%parm[label]%"/>
    </event>
</events>
----

== Microsoft Active Directory Essential Services

=== Windows Services

==== Service: NetLogon
This service is responsible for creating Secure Channel between _Domain Controllers_ and client computers.
Secure Channel is created to pass the authentication packets.
Service performs the registration of `SRV` records, `CNAME` and other `DC` records in the DNS Server to advertise the availability of _Domain Controllers_ in the domain.
`SRV` Records registered by `NetLogon Service` are stored in `C:\Windows\System32\Config\NetLogon.DNS` File.
Performs registration of `SRV` Records every 24 hours depending on the version of Operating System in use.
Registers the `SRV` Records for a site where there is no _Domain Controller_.
This is called _Site Coverege_.

.Windows service monitor for NetLogon in `poller-configuration.xml`
[source,xml]
----
<service name="Win32-NetLogon" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="NetLogon"/>
</service>

<monitor service="Win32-NetLogon" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Service: File Replication Service (FRS)
_File Replication service (FRS)_ is a technology that replicates files and folders stored in the `SYSVOL` shared folder on _Domain Controllers_ and _Distributed File System (DFS)_ shared folders.
When _FRS_ detects that a change has been made to a file or folder within a replicated shared folder, _FRS_ replicates the updated file or folder to other servers.
Because _FRS_ is a multimaster replication service, any server that participates in replication can generate changes.
In addition, _FRS_ can resolve file and folder conflicts to make data consistent among servers.

Further details: http://technet.microsoft.com/en-us/library/cc781582%28v=ws.10%29.aspx[Technet: What Is FRS?]

.Windows service monitor for ???-FRS-Service-Name??? in `poller-configuration.xml`
[source,xml]
----
<service name="Win32-???SERVICE-NAME???" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Task Scheduler"/>
</service>

<service name="Win32-???SERVICE-NAME???" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Task Scheduler"/>
</service>

<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Key Distribution Center
The _Key Distribution Center (KDC)_ is implemented as a domain service.
It uses the _Active Directory_ as its account database and the _Global Catalog_ for directing referrals to _KDCs_ in other domains.
As in other implementations of the _Kerberos_ protocol, the _KDC_ is a single process that provides two services:

- Authentication Service (AS)
  This service issues ticket-granting tickets (TGTs) for connection to the ticket-granting service in its own domain or in any trusted domain.
  Before a client can ask for a ticket to another computer, it must request a TGT from the authentication service in the client's account domain.
  The authentication service returns a TGT for the ticket-granting service in the target computer's domain.
  The TGT can be reused until it expires, but the first access to any domain's ticket-granting service always requires a trip to the authentication service in the client's account domain.

- Ticket-Granting Service (TGS)
  This service issues tickets for connection to computers in its own domain.
  When clients want access to a computer, they contact the ticket-granting service in the target computer's domain, present a TGT, and ask for a ticket to the computer.
  The ticket can be reused until it expires, but the first access to any computer always requires a trip to the ticket-granting service in the target computer's account domain.

*Further details:*

- http://msdn.microsoft.com/en-us/library/windows/desktop/aa378170%28v=vs.85%29.aspx[Technet: Key Distribution Center]

.Windows service monitor for ???-KDC-Service-Name??? in `poller-configuration.xml`
[source,xml]
----
<service name="Win32-???SERVICE-NAME???" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Task Scheduler"/>
</service>

<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Time Synchronization
The _Kerberos_ authentication protocol gets its time from the _Domain Controller_ on which it is running, and it uses that time to determine ticket expiration times and to resolve replication conflicts.
If a time skew of greater than five minutes exists between domain controllers, _Kerberos_ authentication fails, which causes problems in _Active Directory_.
The Windows Time service (`W32Time`) synchronizes the time between domain controllers, which prevents time skews from occurring.

.Windows service monitor for Win32 Time Service in `poller-configuration.xml`
[source,xml]
----
<service name="Win32-Time-Service" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="W32Time"/>
</service>

<monitor service="Win32-Time-Service" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Intersite Messaging
Intersite Messaging is required for _SMTP_ intersite replication and for site coverage calculations.
If the forest functional level is _Windows 2000_, _Intersite Messaging_ is also required for intersite topology generation.

This service enables messages to be exchanged between computers running _Windows Server sites_.
This service is used for mail-based replication between sites.
_Active Directory_ includes support for replication between sites by using _SMTP over IP transport_.
_SMTP_ support is provided by the _SMTP_ service, which is a component of _IIS_.
The set of transports used for communication between sites must be extensible; therefore, each transport is defined in a separate add-in dynamic link library (DLL).
These add-in _DLLs_ are loaded into the _ISM service_, which runs on all _Domain Controllers_ that are candidates for performing communication between sites.
The _ISM service_ directs send requests and receive requests to the appropriate transport add-in DLLs, which then route the messages to the ISM service on the destination computer.

*Further details:*

- http://technet.microsoft.com/en-us/library/cc775549%28v=ws.10%29.aspx[Technet: What Is Active Directory Replication Topology]
- http://technet.microsoft.com/en-us/library/ff799055.aspx[Technet: http://technet.microsoft.com/en-us/library/ff799055.aspx]

.Windows service monitor for ???-ISM-Service-Name??? in `poller-configuration.xml`
[source,xml]
----
<service name="Win32-???SERVICE-NAME???" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="W32Time"/>
</service>

<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

=== Active Directory specific shared folders

.CIFS monitoring for SYSVOL-Share in `poller-configuration.xml`
[source,xml]
----
<service name="CIFS-Share-SYSVOL" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="1" />
    <parameter key="timeout" value="3000" />
    <parameter key="domain" value="contoso" />
    <parameter key="username" value="MonitoringUser" />
    <parameter key="password" value="MonitoringPassword" />
    <parameter key="path" value="SYSLOG" />
    <parameter key="mode" value="path_exist" />
</service>

<monitor service="CIFS-Share-SYSVOL" class-name="org.opennms.netmgt.poller.monitors.JCifsMonitor" />
----

.CIFS monitoring for NetLogon-Share in `poller-configuration.xml`
[source,xml]
----
<service name="CIFS-Share-NetLogon" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="1" />
    <parameter key="timeout" value="3000" />
    <parameter key="domain" value="contoso" />
    <parameter key="username" value="MonitoringUser" />
    <parameter key="password" value="MonitoringPassword" />
    <parameter key="path" value="NETLOGON" />
    <parameter key="mode" value="path_exist" />
</service>

<monitor service="CIFS-Share-NetLogon" class-name="org.opennms.netmgt.poller.monitors.JCifsMonitor" />
----

=== Windows Events throught Traps
The following Event IDs can be forwarded to OpenNMS using the Microsoft SNMP Event Translator (`evntwin.exe`).

.Microsoft Event-IDs to be forwarded as SNMP Traps for Active Directory errors
[options="header"]
|========================
| Event ID | Type  | Rule Group                                                                       | Description
| `1407`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | An Intersite Messaging service request to modify an LDAP object failed
| `1238`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | LDAP agent cannot open security provider
| `1210`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | LDAP connection closed because maximum connections were exceeded
| `1824`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | The Inter-Site Messaging Service cannot perform a requested LDAP bind operation
| `1823`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | The Inter-Site Messaging Service requested to abandon an LDAP notification message
|========================

== Microsoft Exchange 2013

Exchange 2013 Management Pack Health Sets

*Resources:*

- http://technet.microsoft.com/en-us/library/dn195892%28v=exchg.150%29.aspx[Technet: Exchange 2013 Management Pack Health Sets]
- http://docs.blackberry.com/en/admin/deliverables/52733/BlackBerry_Enterprise_Service_10_version_10.1_Configuration_Guide-en.pdf[BES 10.1 Configuration Guide]

== BlackBerry Device Services

== BlackBerry Performance Metrics

=== Server Routing Protocol (SRP)
*Resource:*

- http://www.oidview.com/mibs/3530/BLACKBERRYSERVERMIB-SMIV2.html[BlackBerry Server MIB-SMI v2]

.SNMP OIDS monitoring SRP health state
[options="header"]
|========================
| Name                                  | Description                                                                                                                               | OID
| `besSysHealthSrpConnectedState`       | Indicates whether the BlackBerry Enterprise Server is connected to the wireless network.                                                  | `1.3.6.1.4.1.3530.5.25.1.10`
| `besSysHealthSrpLastConnectDate`      | Indicates the date and time that the BlackBerry Enterprise Server last connected to the wireless network successfully.                    | `1.3.6.1.4.1.3530.5.25.1.11`
| `besSysHealthSrpReconnectSuccess`     | Indicates the number of times that the BlackBerry Enterprise Server has reconnected to the wireless network successfully since startup.   | `1.3.6.1.4.1.3530.5.25.1.12`
| `besSysHealthSrpReconnectsFail`       | Indicates the number of times that the BlackBerry Enterprise Server has failed to connect to the wireless network since startup.          | `1.3.6.1.4.1.3530.5.25.1.13`
| `besSysHealthSrpTotalSecNotConnected` | Indicates the total number of seconds that the BlackBerry Enterprise Server has not been connected to the wireless network since startup. | `1.3.6.1.4.1.3530.5.25.1.14`
| `besSysHealthSrpLastErrorText`        | Indicates the error text associated with the last failed connection attempt.                                                              | `1.3.6.1.4.1.3530.5.25.1.15`
| `besSysHealthSrpLastErrorTime`        | Indicates the date and time of the last connection error.                                                                                 | `1.3.6.1.4.1.3530.5.25.1.16`
|========================

==== SRP Connected State

.SNMP monitor test _BES_ connection state to wireless network
[source,xml]
----
<service name="SRP-Connected-State" interval="300000" user-defined="false" status="on">
    <parameter key="oid" value="1.3.6.1.4.1.3530.5.25.1.10"/>
</service>

<monitor service="SRP-Connected-State" class-name="org.opennms.netmgt.poller.monitors.SnmpMonitor"/>
----

==== SRP reconnect fail and success

.Performance data collection for SRP reconnects in `blackberry.xml`
[source,xml]
----
<?xml version="1.0"?>
<datacollection-group name="BlackBerry">
    <group name="besSysHealthSrp" ifType="ignore">
        <mibObj oid="1.3.6.1.4.1.3530.5.25.1" instance="12" alias="besSrpReconSucc" type="integer" />
        <mibObj oid="1.3.6.1.4.1.3530.5.25.1" instance="13" alias="besSrpReconFail" type="integer" />
        <mibObj oid="1.3.6.1.4.1.3530.5.25.1" instance="14" alias="besSrpTotNoCon" type="timeticks" />
    </group>
    <systemDef name="BlackBerry Enterprise Server">
        <sysoidMask>.1.3.6.1.4.1.3530.</sysoidMask>
        <collect>
            <includeGroup>beSysHealthSrp</includeGroup>
        </collect>
    </systemDef>
</datacollection-group>
----

.Graph definition in `blackberry-graph.properties`
[source,bash]
----
reports=bes.reconnect, \
bes.notconnected

report.bes.reconnect.name=BlackBerry Wireless Reconnect
report.bes.reconnect.columns=besSrpReconSucc, besSrpReconFail
report.bes.reconnect.type=nodeSnmp
report.bes.reconnect.command=--title="BlackBerry Wireless Reconnect" \
 --vertical-label="Number of Times" \
 DEF:val1Avg={rrd1}:besSrpReconSucc:AVERAGE \
 DEF:val1Min={rrd1}:besSrpReconSucc:MIN \
 DEF:val1Max={rrd1}:besSrpReconSucc:MAX \
 DEF:val2Avg={rrd2}:besSrpReconFail:AVERAGE \
 DEF:val2Min={rrd2}:besSrpReconFail:MIN \
 DEF:val2Max={rrd2}:besSrpReconFail:MAX \
 AREA:val1Avg#73d216:"Successful" \
 GPRINT:val1Avg:AVERAGE:"Avg \\: %10.2lf %s" \
 GPRINT:val1Min:MIN:"Min \\: %10.2lf %s" \
 GPRINT:val1Max:MAX:"Max \\: %10.2lf %s\\n" \
 STACK:val2Avg#cc0000:"Failed   " \
 GPRINT:val2Avg:AVERAGE:"Avg \\: %10.2lf %s" \
 GPRINT:val2Min:MIN:"Min \\: %10.2lf %s" \
 GPRINT:val2Max:MAX:"Max \\: %10.2lf %s\\n"

report.bes.notconnected.name=Total number of seconds not connected
report.bes.notconnected.columns=besSrpTotNoCon
report.bes.notconnected.type=nodeSnmp
report.bes.notconnected.command=--title="Total Seconds Not Connected to Wireless" \
 --vertical-label="Total Seconds" \
 DEF:val1Avg={rrd1}:besSrpTotNoCon:AVERAGE \
 DEF:val1Min={rrd1}:besSrpTotNoCon:MIN \
 DEF:val1Max={rrd1}:besSrpTotNoCon:MAX \
 AREA:val1Avg#f57900 \
 LINE2:val1Avg#ce5c00:"Total Seconds" \
 GPRINT:val1Avg:AVERAGE:"Avg \\: %7.3lf%s" \
 GPRINT:val1Min:MIN:"Min \\: %7.3lf%s" \
 GPRINT:val1Max:MAX:"Max \\: %7.3lf%s\\n"
----

=== BlackBerry Windows Services

.Microsoft Windows services to monitor for _BES_
[options="header"]
|========================
| Service name                                                | Description
| `Administration Console`                                    | An administration console that permits you to manage iOS devices and Android devices.
| `BlackBerry Administration Service - Application Server`    | This is the Application Server of the BlackBerry Administration Service.
| `BlackBerry Administration Service - Native Code Container` | This is the Native Code Container of the BlackBerry Administration Service.
| `BlackBerry Controller`                                     | Monitors components and restarts them if they stop responding.
| `BlackBerry Dispatcher`                                     | Performs data encryption and compression services for data that BlackBerry devices send or receive through the BlackBerry Infrastructure.
| `BlackBerry Licensing Service`                              | If registered as the active licensing server, stores the licenses for use.
| `BlackBerry Management Studio`                              | An administration console that permits you to manage BlackBerry devices, iOS devices, and Android devices.
| `BlackBerry MDS Connection Service`                         | Provides a communication channel for BlackBerry devices to access application servers and content servers on your organization's intranet or on the Internet.
| `BlackBerry Secure Connect Service`                         | Maintains a connection through the BlackBerry Infrastructure with the BES10 Client on iOS devices and Android devices.
| `BlackBerry Web Services`                                   | An add-on to the Universal Device Service that contains administrative APIs that are exposed as web services.
| `BlackBerry Work Connect Notification Service`              | Sends notifications to iOS devices when new email messages and calendar entries are available in the Work Connect app.
| `Enterprise Management Web Service`                         | Sends profiles, applications, IT policies, and IT administration commands to BlackBerry devices.
|========================

.Windows service monitor definition in `poller-configuration.xml`
[source,xml]
----
<service name="Win32-BB-Admin-Console" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Administration Console"/>
</service>
<service name="Win32-BBAS-Application-Server" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry Administration Service - Application Server"/>
</service>
<service name="Win32-BBAS-Native-Code-Container" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry Administration Service - Native Code Container"/>
</service>
<service name="Win32-BB-Controller" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry Controller"/>
</service>
<service name="Win32-BB-Dispatcher" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry Dispatcher"/>
</service>
<service name="Win32-BB-Licensing" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry Licensing Service"/>
</service>
<service name="Win32-BB-Management-Studio" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry Management Studio"/>
</service>
<service name="Win32-BB-MDS-Connection" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry MDS Connection Service"/>
</service>
<service name="Win32-BB-Secure-Connection" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry Secure Connect Service"/>
</service>
<service name="Win32-BB-Web-Services" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry Web Services"/>
</service>
<service name="Win32-BB-Work-Connect-Notification" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="BlackBerry Work Connect Notification Service"/>
</service>
<service name="Win32-BB-Enterprise-Management-Web-Service" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Enterprise Management Web Service"/>
</service>

<monitor service="Win32-BB-Admin-Console" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BBAS-Application-Server" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BBAS-Native-Code-Container" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BB-Controller" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BB-Dispatcher" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BB-Licensing" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BB-Management-Studio" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BB-MDS-Connection" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BB-Secure-Connection" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BB-Web-Services" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BB-Work-Connect-Notification" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-BB-Enterprise-Management-Web-Service" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

=== BlackBerry HTTP and HTTPS based services

==== HTTP access to Admin Service
This component monitor tests the ability of a _BES Admin service_ to accept incoming sessions by HTTP.
By default port is `38180`.

.Monitoring with HTTP in `poller-configuration.xml`
[source,xml]
----
<service name="HTTP-BlackBerry-Admin-Service" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="3"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="38180"/>
    <parameter key="response" value="200-202,299"/>
</service>

<monitor service="HTTP-BlackBerry-Admin-Service" class-name="org.opennms.netmgt.poller.monitors.HttpMonitor"/>
----

==== HTTPS access to Admin Service
This component monitor tests the ability of a _BES Admin service_ to accept incoming sessions by HTTPS.
By default port is `38443`.

.Monitoring HTTPS in `poller-configuration.xml`
[source,xml]
----
<service name="HTTPS-BlackBerry-Admin-Service" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="3"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="38443"/>
    <parameter key="response" value="200-202,299"/>
</service>

<monitor service="HTTPS-BlackBerry-Admin-Service" class-name="org.opennms.netmgt.poller.monitors.HttpsMonitor"/>
----

==== HTTPS access to Licensing Server
This component monitor tests the ability of a _BES Licensing service_ to accept incoming sessions by HTTPS.
By default port is `3333`.

.Monitoring connectivity to Licensing Server in `poller-configuration.xml`
[source,xml]
----
<service name="HTTPS-BlackBerry-Licensing-Server" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="3"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="3333"/>
    <parameter key="response" value="200-202,299"/>
</service>

<monitor service="HTTPS-BlackBerry-Licensing-Server" class-name="org.opennms.netmgt.poller.monitors.HttpsMonitor"/>
----

==== HTTPS access to Universal Device Service
This component monitor tests the ability of a _BES Universal Device service_ to accept incoming sessions by HTTPS.
By default port is `6443`.

.Monitoring connectivity to Universal Device Service in `poller-configuration.xml`
[source,xml]
----
<service name="HTTPS-BlackBerry-Universal-Device-Service" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="3"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="6443"/>
    <parameter key="response" value="200-202,299"/>
</service>

<monitor service="HTTPS-BlackBerry-Universal-Device-Service" class-name="org.opennms.netmgt.poller.monitors.HttpsMonitor"/>
----

==== HTTPS access to BlackBerry Management Studio
This component monitor tests the ability of a _BES Management Studio_ to accept incoming sessions by HTTPS.
By default port is `7443`.

.Monitoring connectivity to Management Studio in `poller-configuration.xml`
[source,xml]
----
<service name="HTTPS-BlackBerry-Management-Studio" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="3"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="7443"/>
    <parameter key="response" value="200-202,299"/>
</service>

<monitor service="HTTPS-BlackBerry-Management-Studio" class-name="org.opennms.netmgt.poller.monitors.HttpsMonitor"/>
----
