= Monitoring Black Berry 10

== Basic network availability

=== ICMP

=== DNS name resolution

[source, xml]
----
<service name="DNS-Resolution-v6" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="2000"/>
    <parameter key="resolution-type" value="v4"/>
    <parameter key="rrd-repository" value="/opt/opennms/share/rrd/response"/>
    <parameter key="rrd-base-name" value="dns-res-v6"/>
    <parameter key="ds-name" value="dns-res-v6"/>
</service>
<service name="DNS-Resolution-v6" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="2000"/>
    <parameter key="resolution-type" value="v6"/>
    <parameter key="rrd-repository" value="/opt/opennms/share/rrd/response"/>
    <parameter key="rrd-base-name" value="dns-res-v6"/>
    <parameter key="ds-name" value="dns-res-v6"/>
</service>

<monitor service="DNS-Resolution-v4" class-name="org.opennms.netmgt.poller.monitors.DNSResolutionMonitor" />
<monitor service="DNS-Resolution-v6" class-name="org.opennms.netmgt.poller.monitors.DNSResolutionMonitor" />
----
== Baselining basic system metrics
Requirements for default system monitoring is installed and configured Windows SNMP agent + SNMP informant Standard.
http://www.snmp-informant.com/[SNMP Informant] is required to monitor Windows CPU utiliziation correctly.
Restart of the Windows System reogranises the CPU number SNMP index on Multi-Core systems.

=== Hard disk

=== CPU

.Category based thresholding configuration in `threshd-configuration.xml`
[source, xml]
----
<package name="TH-DISK-90">
    <filter>catincTH-DISK-90</filter>
    <include-range begin="1.1.1.1" end="254.254.254.254"/>
    <include-range begin="::1" end="ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff" />
    <service name="SNMP" interval="300000" user-defined="false" status="on">
        <parameter key="thresholding-group" value="TH-DISK-90"/>
    </service>
</package>

<package name="TH-CPU-90">
    <filter>catincTH-CPU-90</filter>
    <include-range begin="1.1.1.1" end="254.254.254.254"/>
    <include-range begin="::1" end="ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff" />
    <service name="SNMP" interval="300000" user-defined="false" status="on">
        <parameter key="thresholding-group" value="TH-CPU-90"/>
    </service>
</package>
----


.Configuration of Microsoft Windows and Linux CPU thresholds
[source, xml]
----
<group name="TH-CPU-90" rrdRepository="/var/lib/opennms/rrd/snmp/">
    <threshold description="cpu high threshold 90.0 rearmed 70.0 (Windows Single)"
               type="high" ds-type="sinfCpuInstance"
               value="90.0" rearm="70.0" trigger="5"
               ds-label="sinfCpuInstance"
               triggeredUEI="uei.opennms.org/threshold/windows/cpu/high/major/exceeded"
               rearmedUEI="uei.opennms.org/threshold/windows/cpu/high/major/rearmed"
               filterOperator="or" ds-name="sinfCpuPctProcTime">
        <resource-filter field="sinfCpuInstance">^\d+</resource-filter>
    </threshold>
    <threshold description="cpu high threshold 90.0 rearmed 70.0 (Windows Total)"
               type="high" ds-type="sinfCpuInstance"
               value="90.0" rearm="70.0" trigger="2"
               ds-label="sinfCpuInstance"
               triggeredUEI="uei.opennms.org/threshold/windows/cpu/high/major/exceeded"
               rearmedUEI="uei.opennms.org/threshold/windows/cpu/high/major/rearmed"
               filterOperator="or" ds-name="sinfCpuPctProcTime">
        <resource-filter field="sinfCpuInstance">^_Total</resource-filter>
    </threshold>
    <expression description="cpu high threshold 90.0 rearmed 70.0 (Unix Total)"
                type="high" ds-type="node"
                value="90.0" rearm="70.0"
                trigger="2"
                triggeredUEI="uei.opennms.org/threshold/unix/cpu/high/major/exceeded"
                rearmedUEI="uei.opennms.org/threshold/unix/cpu/high/major/rearmed"
                filterOperator="or"
                expression="(CpuRawUser+CpuRawNice+CpuRawSystem) / (CpuRawUser+CpuRawNice+CpuRawSystem+CpuRawIdle) *100"/>
----

.Configuration for generic hard disk thresholds
[source, xml]
----
</group>
    <group name="TH-DISK-90" rrdRepository="/var/lib/opennms/rrd/snmp/">
    <expression description="disk usage high 90.0 and rearmed 75.0"
                type="high" ds-type="hrStorageIndex"
                value="90.0" rearm="75.0" trigger="2"
                ds-label="hrStorageDescr"
                triggeredUEI="uei.opennms.org/threshold/disk/high/major/exceeded"
                rearmedUEI="uei.opennms.org/threshold/disk/high/major/rearmed"
                filterOperator="or"
                expression="hrStorageUsed / hrStorageSize * 100.0">
        <resource-filter field="hrStorageType">^\.1\.3\.6\.1\.2\.1\.25\.2\.1\.4$</resource-filter>
    </expression>
</group>
----

=== Events for OpenNMS Web UI

[source, xml]
----
<events>
    <event>
        <uei>uei.opennms.org/threshold/windows/cpu/high/major/exceeded</uei>
        <event-label>User-defined custom high threshold exceeded event for windows-cpu [Major]</event-label>
        <descr>
            &lt;p&gt;High threshold exceeded for %service% datasource %parm[ds]% on interface %interface% for node %nodelabel% (nodeId %nodeid%).&lt;/p&gt;&lt;br&gt;
            &lt;table style='width:50%; white-space: nowrap;'&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Data Source&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[ds]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Label&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[label]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Instance&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[instance]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Current Metric Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[value]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Threshold Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[threshold]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Rearm Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[rearm]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Trigger Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[trigger]%&lt;/td&gt;&lt;/tr&gt;
            &lt;/table&gt; &lt;/br&gt;&lt;p&gt;All parameters: %parm[all]%&lt;/p&gt;
        </descr>
        <logmsg dest="logndisplay">&lt;b&gt;&lt;a href='graph/results.htm?resourceId=node[%nodeid%].sinfCpuInstance[%parm[instance]%]&amp;reports=all'&gt;WINDOWS-CPU&lt;/b&gt;&lt;/a&gt; HIGH threshold &lt;b&gt;%parm[threshold]%&lt;/b&gt; exceeded with &lt;font color=#cc0000&gt;&lt;b&gt;%parm[value]%&lt;/b&gt;&lt;/font&gt;, on instance &lt;b&gt;%parm[label]%&lt;/b&gt;, for metric %parm[ds]%, on node %nodelabel%.</logmsg>
        <severity>Major</severity>
        <alarm-data auto-clean="false" alarm-type="1" reduction-key="%uei%:%dpname%:%nodeid%:%interface%:%parm[ds]%:%parm[threshold]%:%parm[trigger]%:%parm[rearm]%:%parm[label]%"/>
    </event>
    <event>
        <uei>uei.opennms.org/threshold/unix/cpu/high/major/exceeded</uei>
        <event-label>User-defined custom high threshold exceeded event for unix-cpu [Major]</event-label>
        <descr>
            &lt;p&gt;High threshold exceeded for %service% datasource %parm[ds]% on interface %interface% for node %nodelabel% (nodeId %nodeid%).&lt;/p&gt;&lt;br&gt;
            &lt;table style='width:50%; white-space: nowrap;'&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Data Source&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[ds]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Label&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[label]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Instance&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[instance]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Current Metric Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[value]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Threshold Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[threshold]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Rearm Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[rearm]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Trigger Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[trigger]%&lt;/td&gt;&lt;/tr&gt;
            &lt;/table&gt; &lt;/br&gt;&lt;p&gt;All parameters: %parm[all]%&lt;/p&gt;
        </descr>
        <logmsg dest="logndisplay">&lt;b&gt;&lt;a href='graph/results.htm?resourceId=node[%nodeid%].nodeSnmp[]&amp;reports=netsnmp.cpuStatsFull&amp;reports=netsnmp.cpuUsageFull'&gt;UNIX-CPU&lt;/b&gt;&lt;/a&gt; HIGH threshold &lt;b&gt;%parm[threshold]%&lt;/b&gt; exceeded with &lt;font color=#cc0000&gt;&lt;b&gt;%parm[value]%&lt;/b&gt;&lt;/font&gt;, for metric %parm[ds]%, on node %nodelabel%.</logmsg>
        <severity>Major</severity>
        <alarm-data auto-clean="false" alarm-type="1" reduction-key="%uei%:%dpname%:%nodeid%:%interface%:%parm[ds]%:%parm[threshold]%:%parm[trigger]%:%parm[rearm]%:%parm[label]%"/>
    </event>
    <event>
        <uei>uei.opennms.org/threshold/disk/high/major/exceeded</uei>
        <event-label>User-defined custom high threshold exceeded event for disk [Major]</event-label>
        <descr>
            &lt;p&gt;High threshold exceeded for %service% datasource %parm[ds]% on interface %interface% for node %nodelabel% (nodeId %nodeid%).&lt;/p&gt;&lt;br&gt;
            &lt;table style='width:50%; white-space: nowrap;'&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Data Source&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[ds]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Label&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[label]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Resource Instance&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[instance]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Current Metric Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[value]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Threshold Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[threshold]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Rearm Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[rearm]%&lt;/td&gt;&lt;/tr&gt;
            &lt;tr&gt;&lt;td&gt;&lt;b&gt;Trigger Value&lt;/b&gt;&lt;/td&gt;&lt;td&gt;%parm[trigger]%&lt;/td&gt;&lt;/tr&gt;
            &lt;/table&gt; &lt;/br&gt;&lt;p&gt;All parameters: %parm[all]%&lt;/p&gt;</descr>
        <logmsg dest="logndisplay">&lt;b&gt;DISK&lt;/b&gt; HIGH threshold &lt;b&gt;%parm[threshold]%&lt;/b&gt; exceeded with &lt;font color=#cc0000&gt;&lt;b&gt;%parm[value]%&lt;/b&gt;&lt;/font&gt;, on instance &lt;b&gt;%parm[label]%&lt;/b&gt;, for metric %parm[ds]%, on node %nodelabel%.</logmsg>
        <severity>Major</severity>
        <alarm-data auto-clean="false" alarm-type="1" reduction-key="%uei%:%dpname%:%nodeid%:%interface%:%parm[ds]%:%parm[threshold]%:%parm[trigger]%:%parm[rearm]%:%parm[label]%"/>
    </event>
</events>
----

== Microsoft Active Directory Essential Services

=== Windows Services

==== Service: NetLogon
This service is responsible for creating Secure Channel between _Domain Controllers_ and client computers.
Secure Channel is created to pass the authentication packets.
Service performs the registration of `SRV` records, `CNAME` and other `DC` records in the DNS Server to advertise the availability of _Domain Controllers_ in the domain.
`SRV` Records registered by `NetLogon Service` are stored in `C:\Windows\System32\Config\NetLogon.DNS` File.
Performs registration of `SRV` Records every 24 hours depending on the version of Operating System in use.
Registers the `SRV` Records for a site where there is no _Domain Controller_.
This is called _Site Coverege_.

[source, xml]
----
<service name="Win32-NetLogon" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="NetLogon"/>
</service>

<monitor service="Win32-NetLogon" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Service: File Replication Service (FRS)
_File Replication service (FRS)_ is a technology that replicates files and folders stored in the `SYSVOL` shared folder on _Domain Controllers_ and _Distributed File System (DFS)_ shared folders.
When _FRS_ detects that a change has been made to a file or folder within a replicated shared folder, _FRS_ replicates the updated file or folder to other servers.
Because _FRS_ is a multimaster replication service, any server that participates in replication can generate changes.
In addition, _FRS_ can resolve file and folder conflicts to make data consistent among servers.

Further details: http://technet.microsoft.com/en-us/library/cc781582%28v=ws.10%29.aspx[Technet: What Is FRS?]
[source, xml]
----
<service name="Win32-???SERVICE-NAME???" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Task Scheduler"/>
</service>

<service name="Win32-???SERVICE-NAME???" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Task Scheduler"/>
</service>

<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Key Distribution Center
The _Key Distribution Center (KDC)_ is implemented as a domain service.
It uses the _Active Directory_ as its account database and the _Global Catalog_ for directing referrals to _KDCs_ in other domains.
As in other implementations of the _Kerberos_ protocol, the _KDC_ is a single process that provides two services:

- Authentication Service (AS)
  This service issues ticket-granting tickets (TGTs) for connection to the ticket-granting service in its own domain or in any trusted domain.
  Before a client can ask for a ticket to another computer, it must request a TGT from the authentication service in the client's account domain.
  The authentication service returns a TGT for the ticket-granting service in the target computer's domain.
  The TGT can be reused until it expires, but the first access to any domain's ticket-granting service always requires a trip to the authentication service in the client's account domain.

- Ticket-Granting Service (TGS)
  This service issues tickets for connection to computers in its own domain.
  When clients want access to a computer, they contact the ticket-granting service in the target computer's domain, present a TGT, and ask for a ticket to the computer.
  The ticket can be reused until it expires, but the first access to any computer always requires a trip to the ticket-granting service in the target computer's account domain.

*Further details:*

- http://msdn.microsoft.com/en-us/library/windows/desktop/aa378170%28v=vs.85%29.aspx[Technet: Key Distribution Center]

[source, xml]
----
<service name="Win32-???SERVICE-NAME???" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Task Scheduler"/>
</service>

<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Time Synchronization
The _Kerberos_ authentication protocol gets its time from the _Domain Controller_ on which it is running, and it uses that time to determine ticket expiration times and to resolve replication conflicts.
If a time skew of greater than five minutes exists between domain controllers, _Kerberos_ authentication fails, which causes problems in _Active Directory_.
The Windows Time service (`W32Time`) synchronizes the time between domain controllers, which prevents time skews from occurring.

[source, xml]
----
<service name="Win32-Time-Service" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="W32Time"/>
</service>

<monitor service="Win32-Time-Service" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Intersite Messaging
Intersite Messaging is required for _SMTP_ intersite replication and for site coverage calculations.
If the forest functional level is _Windows 2000_, _Intersite Messaging_ is also required for intersite topology generation.

This service enables messages to be exchanged between computers running _Windows Server sites_.
This service is used for mail-based replication between sites.
_Active Directory_ includes support for replication between sites by using _SMTP over IP transport_.
_SMTP_ support is provided by the _SMTP_ service, which is a component of _IIS_.
The set of transports used for communication between sites must be extensible; therefore, each transport is defined in a separate add-in dynamic link library (DLL).
These add-in _DLLs_ are loaded into the _ISM service_, which runs on all _Domain Controllers_ that are candidates for performing communication between sites.
The _ISM service_ directs send requests and receive requests to the appropriate transport add-in DLLs, which then route the messages to the ISM service on the destination computer.

*Further details:*

- http://technet.microsoft.com/en-us/library/cc775549%28v=ws.10%29.aspx[Technet: What Is Active Directory Replication Topology]
- http://technet.microsoft.com/en-us/library/ff799055.aspx[Technet: http://technet.microsoft.com/en-us/library/ff799055.aspx]

[source, xml]
----
<service name="Win32-???SERVICE-NAME???" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="W32Time"/>
</service>

<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

=== Active Directory specific shared folders

[source, xml]
----
<service name="CIFS-Share-SYSVOL" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="1" />
    <parameter key="timeout" value="3000" />
    <parameter key="domain" value="contoso" />
    <parameter key="username" value="MonitoringUser" />
    <parameter key="password" value="MonitoringPassword" />
    <parameter key="path" value="SYSLOG" />
    <parameter key="mode" value="path_exist" />
</service>

<monitor service="CIFS-Share-SYSVOL" class-name="org.opennms.netmgt.poller.monitors.JCifsMonitor" />
----

[source, xml]
----
<service name="CIFS-Share-NETLOGON" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="1" />
    <parameter key="timeout" value="3000" />
    <parameter key="domain" value="contoso" />
    <parameter key="username" value="MonitoringUser" />
    <parameter key="password" value="MonitoringPassword" />
    <parameter key="path" value="NETLOGON" />
    <parameter key="mode" value="path_exist" />
</service>

<monitor service="CIFS-Share-NETLOGON" class-name="org.opennms.netmgt.poller.monitors.JCifsMonitor" />
----

=== Windows Events throught Traps
The following Event IDs can be forwarded to OpenNMS using the Microsoft SNMP Event Translator (`evntwin.exe`).

[options="header"]
|========================
| Event ID | Type  | Rule Group                                                                       | Description
| `1407`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | An Intersite Messaging service request to modify an LDAP object failed
| `1238`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | LDAP agent cannot open security provider
| `1210`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | LDAP connection closed because maximum connections were exceeded
| `1824`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | The Inter-Site Messaging Service cannot perform a requested LDAP bind operation
| `1823`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | The Inter-Site Messaging Service requested to abandon an LDAP notification message
|========================

== Microsoft Exchange 2013

Exchange 2013 Management Pack Health Sets

*Resources:*

- http://technet.microsoft.com/en-us/library/dn195892%28v=exchg.150%29.aspx[Technet: Exchange 2013 Management Pack Health Sets]
- http://docs.blackberry.com/en/admin/deliverables/52733/BlackBerry_Enterprise_Service_10_version_10.1_Configuration_Guide-en.pdf[BES 10.1 Configuration Guide]

== BlackBerry Device Services

== BlackBerry Performance Metrics

=== Server Routing Protocol (SRP)
*Resource:*

- http://www.oidview.com/mibs/3530/BLACKBERRYSERVERMIB-SMIV2.html[BlackBerry Server MIB-SMI v2]

[options="header"]
|========================
| Name                                  | Description                                                                                                                               | OID
| `besSysHealthSrpConnectedState`       | Indicates whether the BlackBerry Enterprise Server is connected to the wireless network.                                                  | `1.3.6.1.4.1.3530.5.25.1.10`
| `besSysHealthSrpLastConnectDate`      | Indicates the date and time that the BlackBerry Enterprise Server last connected to the wireless network successfully.                    | `1.3.6.1.4.1.3530.5.25.1.11`
| `besSysHealthSrpReconnectSuccess`     | Indicates the number of times that the BlackBerry Enterprise Server has reconnected to the wireless network successfully since startup.   | `1.3.6.1.4.1.3530.5.25.1.12`
| `besSysHealthSrpReconnectsFail`       | Indicates the number of times that the BlackBerry Enterprise Server has failed to connect to the wireless network since startup.          | `1.3.6.1.4.1.3530.5.25.1.13`
| `besSysHealthSrpTotalSecNotConnected` | Indicates the total number of seconds that the BlackBerry Enterprise Server has not been connected to the wireless network since startup. | `1.3.6.1.4.1.3530.5.25.1.14`
| `besSysHealthSrpLastErrorText`        | Indicates the error text associated with the last failed connection attempt.                                                              | `1.3.6.1.4.1.3530.5.25.1.15`
| `besSysHealthSrpLastErrorTime`        | Indicates the date and time of the last connection error.                                                                                 | `1.3.6.1.4.1.3530.5.25.1.16`
|========================

=== BlackBerry Controller

=== BlackBerry Dispatcher

=== BlackBerry Router

=== BlackBerry MDS Connection Service
