= Monitoring Black Berry 10

== Microsoft Active Directory Essential Services

=== Windows Services

==== Service: NetLogon
This service is responsible for creating Secure Channel between _Domain Controllers_ and client computers.
Secure Channel is created to pass the authentication packets.
Service performs the registration of `SRV` records, `CNAME` and other `DC` records in the DNS Server to advertise the availability of _Domain Controllers_ in the domain.
`SRV` Records registered by `NetLogon Service` are stored in `C:\Windows\System32\Config\NetLogon.DNS` File.
Performs registration of `SRV` Records every 24 hours depending on the version of Operating System in use.
Registers the `SRV` Records for a site where there is no _Domain Controller_.
This is called _Site Coverege_.

[source, xml]
----
<service name="Win32-NetLogon" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="NetLogon"/>
</service>

<monitor service="Win32-NetLogon" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Service: File Replication Service (FRS)
_File Replication service (FRS)_ is a technology that replicates files and folders stored in the `SYSVOL` shared folder on _Domain Controllers_ and _Distributed File System (DFS)_ shared folders.
When _FRS_ detects that a change has been made to a file or folder within a replicated shared folder, _FRS_ replicates the updated file or folder to other servers.
Because _FRS_ is a multimaster replication service, any server that participates in replication can generate changes.
In addition, _FRS_ can resolve file and folder conflicts to make data consistent among servers.

Further details: http://technet.microsoft.com/en-us/library/cc781582%28v=ws.10%29.aspx[Technet: What Is FRS?]
[source, xml]
----
<service name="Win32-???SERVICE-NAME???" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Task Scheduler"/>
</service>

<service name="Win32-???SERVICE-NAME???" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Task Scheduler"/>
</service>

<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Key Distribution Center
The _Key Distribution Center (KDC)_ is implemented as a domain service.
It uses the _Active Directory_ as its account database and the _Global Catalog_ for directing referrals to _KDCs_ in other domains.
As in other implementations of the _Kerberos_ protocol, the _KDC_ is a single process that provides two services:

- Authentication Service (AS)
  This service issues ticket-granting tickets (TGTs) for connection to the ticket-granting service in its own domain or in any trusted domain.
  Before a client can ask for a ticket to another computer, it must request a TGT from the authentication service in the client's account domain.
  The authentication service returns a TGT for the ticket-granting service in the target computer's domain.
  The TGT can be reused until it expires, but the first access to any domain's ticket-granting service always requires a trip to the authentication service in the client's account domain.

- Ticket-Granting Service (TGS)
  This service issues tickets for connection to computers in its own domain.
  When clients want access to a computer, they contact the ticket-granting service in the target computer's domain, present a TGT, and ask for a ticket to the computer.
  The ticket can be reused until it expires, but the first access to any computer always requires a trip to the ticket-granting service in the target computer's account domain.

*Further details:*

- http://msdn.microsoft.com/en-us/library/windows/desktop/aa378170%28v=vs.85%29.aspx[Technet: Key Distribution Center]

[source, xml]
----
<service name="Win32-???SERVICE-NAME???" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="Task Scheduler"/>
</service>

<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Time Synchronization
The _Kerberos_ authentication protocol gets its time from the _Domain Controller_ on which it is running, and it uses that time to determine ticket expiration times and to resolve replication conflicts.
If a time skew of greater than five minutes exists between domain controllers, _Kerberos_ authentication fails, which causes problems in _Active Directory_.
The Windows Time service (`W32Time`) synchronizes the time between domain controllers, which prevents time skews from occurring.

[source, xml]
----
<service name="Win32-Time-Service" interval="300000" user-defined="false" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="W32Time"/>
</service>

<monitor service="Win32-Time-Service" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

==== Intersite Messaging
Intersite Messaging is required for _SMTP_ intersite replication and for site coverage calculations.
If the forest functional level is _Windows 2000_, _Intersite Messaging_ is also required for intersite topology generation.

This service enables messages to be exchanged between computers running _Windows Server sites_.
This service is used for mail-based replication between sites.
_Active Directory_ includes support for replication between sites by using _SMTP over IP transport_.
_SMTP_ support is provided by the _SMTP_ service, which is a component of _IIS_.
The set of transports used for communication between sites must be extensible; therefore, each transport is defined in a separate add-in dynamic link library (DLL).
These add-in _DLLs_ are loaded into the _ISM service_, which runs on all _Domain Controllers_ that are candidates for performing communication between sites.
The _ISM service_ directs send requests and receive requests to the appropriate transport add-in DLLs, which then route the messages to the ISM service on the destination computer.

*Further details:*

- http://technet.microsoft.com/en-us/library/cc775549%28v=ws.10%29.aspx[Technet: What Is Active Directory Replication Topology]
- http://technet.microsoft.com/en-us/library/ff799055.aspx[Technet: http://technet.microsoft.com/en-us/library/ff799055.aspx]

[source, xml]
----
<service name="Win32-???SERVICE-NAME???" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="port" value="161"/>
    <parameter key="service-name" value="W32Time"/>
</service>

<monitor service="Win32-???SERVICE-NAME???" class-name="org.opennms.netmgt.poller.monitors.Win32ServiceMonitor"/>
----

=== Active Directory specific shared folders

[source, xml]
----
<service name="CIFS-Share-SYSVOL" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="1" />
    <parameter key="timeout" value="3000" />
    <parameter key="domain" value="contoso" />
    <parameter key="username" value="MonitoringUser" />
    <parameter key="password" value="MonitoringPassword" />
    <parameter key="path" value="SYSLOG" />
    <parameter key="mode" value="path_exist" />
</service>

<monitor service="CIFS-Share-SYSVOL" class-name="org.opennms.netmgt.poller.monitors.JCifsMonitor" />
----

[source, xml]
----
<service name="CIFS-Share-NETLOGON" interval="30000" user-defined="true" status="on">
    <parameter key="retry" value="1" />
    <parameter key="timeout" value="3000" />
    <parameter key="domain" value="contoso" />
    <parameter key="username" value="MonitoringUser" />
    <parameter key="password" value="MonitoringPassword" />
    <parameter key="path" value="NETLOGON" />
    <parameter key="mode" value="path_exist" />
</service>

<monitor service="CIFS-Share-NETLOGON" class-name="org.opennms.netmgt.poller.monitors.JCifsMonitor" />
----

=== Windows Events throught Traps
The following Event IDs can be forwarded to OpenNMS using the Microsoft SNMP Event Translator (`evntwin.exe`).

[options="header"]
|========================
| Event ID | Type  | Rule Group                                                                       | Description
| `1407`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | An Intersite Messaging service request to modify an LDAP object failed
| `1238`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | LDAP agent cannot open security provider
| `1210`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | LDAP connection closed because maximum connections were exceeded
| `1824`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | The Inter-Site Messaging Service cannot perform a requested LDAP bind operation
| `1823`   | Error | Active Directory Windows 2000 and Windows Server 2003 - Active Directory General | The Inter-Site Messaging Service requested to abandon an LDAP notification message
|========================

== BlackBerry Device Services

Resource: http://docs.blackberry.com/en/admin/deliverables/52733/BlackBerry_Enterprise_Service_10_version_10.1_Configuration_Guide-en.pdf[BES 10.1 Configuration Guide]

=== BlackBerry Controller

=== BlackBerry Dispatcher

=== BlackBerry Router

=== BlackBerry MDS Connection Service
